src/OCPlatformBundle/Entity/Image.php
<?php

namespace OCPlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="OCPlatformBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    private $file;

    private $tempFilename;

    public function getFile()
    {
        return $this->file;
    }

    public function setFile( UploadedFile $file = null )
    {
        $this->file  = $file;

        if( null !== $this->url ){

            $tempFilename = $this->url;

            $this->url = null;
            $this->alt = null;

        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload(){

        if(null === $this->file){
            return;
        }
         
         $this->url = $this->file->guessExtension();

         $this->alt = $this->file->getClientOriginalName();

    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if(null === $this->file){
            return;
        }

        if(null !== $this->tempFilename){
                $oldFile = $this->getUploadRootDir().'/'. $this->id .'.'. $this->tempFilename;
            if( file_exists($oldFile) ){
                unlink($oldFile);
            }
        }

        $this->file->move( 
            $this->getUploadRootDir(), 
            $this->id . '.' . $this->url
         );

    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
       $this->tempFilename = $this->getUploadRootDir().'/'. $this->id .'.'. $this->url; 
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
    
        if( file_exists($this->tempFilename) ){
                unlink($this->tempFilename);
            }
    }

    public function getUploadDir()
    {
        return 'uploads/img';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        //return  $this->getUploadRootDir().'/'.$this->getId().'.'.$this->getUrl(); 
        return  '/Symfony/web/'.$this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl(); 
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string 
     */
    public function getAlt()
    {
        return $this->alt;
    }
}

src/OCPlatformBundle/Form/PublicationType.php
<?php

namespace OCPlatformBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PublicationType extends AdvertType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->remove('date');

    }
    
   
    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'ocplatformbundle_advert_edit';
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return new AdvertType() ;
    }

}

src/OCPlatformBundle/Controller/PublicationController.php
<?php 

namespace OCPlatformBundle\Controller;

use OCPlatformBundle\Entity\Advert;
use OCPlatformBundle\Entity\AdvertSkill;
use OCPlatformBundle\Entity\Image;
use OCPlatformBundle\Entity\Application;
use OCPlatformBundle\Form\AdvertType;
use OCPlatformBundle\Form\AdvertEditType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
* 
*/
class PublicationController extends Controller 
{

	
	public function indexAction($page){



		if ($page<1) {
			throw new NotFoundHttpException('page "'.$page.'" inexistante');
		}
		
		$nbPerPage = 3;
		
		$listAdverts  = $this->getDoctrine()->getRepository('OCPlatformBundle:Advert')
							 ->getAdverts($page,$nbPerPage);

		$nbPages = ceil(count($listAdverts)/ $nbPerPage );

		
		return $this->render('OCPlatformBundle:Advert:index.html.twig', 
		 array(
		 		
		 		'listAdverts' => $listAdverts,
		 		'nbPages'     => $nbPages,
		 		'page'        => $page 
		 	)
		);

	}

	public function viewAction($id/*, Request $request*/){


		$em = $this->getDoctrine()->getManager();

		$repository = $em->getRepository('OCPlatformBundle:Advert');
		$advert = $repository->find($id);

		$listApplications = $em->getRepository('OCPlatformBundle:Application')->findBy(array('advert' => $advert ));

		if (null === $advert) {
			

				throw new NotFoundHttpException("l'annonce d'id ".$id." n'existe pas");
			
		}

		$listAdvertSkills = $em->getRepository('OCPlatformBundle:AdvertSkill')->findByAdvert($advert);



		return $this->render( 'OCPlatformBundle:Advert:view.html.twig', array( 'advert' => $advert,
		                                                                       'listApplications' => $listApplications, 
		                                                                        'listAdvertSkills' => $listAdvertSkills  ) );
		
	}

	
	public function viewSlugAction($slug, $year, $format){
		 return new Response("Affichage du slug : ".$slug." crée en ".$year." et au format ".$format);
	}

	public function addAction(Request $request){


		if ( !$this->get('security.context')->isGranted('ROLE_AUTEUR')) {
			throw new AccessDeniedException('Accès limité aux auteurs');
		}

		$advert = new Advert();

		$form = $this->get('form.factory')->create(new AdvertType(), $advert);
		

		if ($form->handleRequest($request)->isValid()) {

			$em = $this->getDoctrine()->getManager();
			$em->persist($advert);
			$em->flush();

			$request->getSession()->getFlashBag()->add('notice', 'Annonce bien enregistrée');
			return $this->redirect($this->generateUrl( 'oc_platform_view', array('id' => $advert->getId() ) ) );
		}

		return $this->render('OCPlatformBundle:Advert:add.html.twig' , array('form' => $form->createView()) );
		
		
	}

	public function editAction($id, Request $request){

        $em = $this->getDoctrine()->getManager();
        $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);

        if (null === $advert) {
        	throw  $this->createNotFoundException("l'annonce d'id ".$id." n'existe pas");
        }

	
		$form = $this->get('form.factory')->create(new AdvertEditType(), $advert);
		

		if ($form->handleRequest($request)->isValid()) {

			$em->flush();

			$request->getSession()->getFlashBag()->add('notice', 'Annonce bien modifiée');
			return $this->redirect($this->generateUrl( 'oc_platform_view', array('id' => $advert->getId() ) ) );
		}

		return $this->render('OCPlatformBundle:Advert:edit.html.twig' , array('form' => $form->createView(),
																			  'advert' => $advert 
																			) );
	}

	public function deleteAction($id, Request $request){

		$em = $this->getDoctrine()->getManager();

		$advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);

		if (null === $advert) {
			throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas ");	
		}

		$form = $this->createFormBuilder()->getForm();
		if ($form->handleRequest($request)->isValid() ) {

			$em->remove($advert);

			$em->flush();

			$request->getSession()->getFlashBag()->add('info', 'Annonce bien supprimée');

		
			return $this->redirect($this->generateUrl('oc_platform_home'));
		}		

		return $this->render('OCPlatformBundle:Advert:delete.html.twig' , array( 
			                                                             'advert' => $advert,
			                                                              'form'  => $form->createView() ));
		
	}

	public function menuAction($limit = 3)
  {

    $listAdverts = $this->getDoctrine()->getManager()->getRepository('OCPlatformBundle:Advert')->
    					findBy(
    							array(),
    							array('date' => 'DESC' ),
    							$limit,
    							0
    					);

    return $this->render('OCPlatformBundle:Advert:menu.html.twig', array(
 
      'listAdverts' => $listAdverts
    ));
  }

  public function shareAction($id)
  {
    $em = $this->getDoctrine()->getManager();

    $publication = $em->getRepository('PlatformBundle:Publication')->find($id);

    if ($publication === null) {
      throw $this->createNotFoundException("La publication d'id ".$id." n'existe pas.");
    }

    if ($publication->getOrigin() != null) {
      $publication =  $publication->getOrigin();
    }

    $listPublications = $em->getRepository('PlatformBundle:Publication')->findBy(array(
                                                                    'author' => $this->getUser(),
                                                                    'origin' => $publication ) ); //
    $request = $this->container->get('request');
    
    if($listPublications){

      $request->getSession()->getFlashBag()->add('notice', 'Vous avez déja partagé cette publication');
      return $this->redirectToRoute('publication_view', array('id' => $publication->getId() ));
    }
	$sharing = new Publication();
    $image = new Image(); 
    try {
      $sharing->setOrigin($publication);
      $sharing->setTitle( $this->getUser()->getFirstname() . "a partagé une publication de "
                                  . $publication->getAuthor()->getFirstname()  );
      $sharing->setAuthor($this->getUser());
      $sharing->setContent($publication->getContent());

      $image->setUrl( $publication->getImage()->getUrl() );
      $image->setAlt( $publication->getImage()->getAlt() );
      $sharing->setImage($image);
      $sharing->setLikes( $publication->getLikes() );

      $em->persist($sharing);
      $em->flush();

      $request->getSession()->getFlashBag()->add('notice', 'Votre partage est enregistré');
      return $this->redirectToRoute('publication_view', array('id' => $sharing->getId() ));

    } catch (Exception $e) {
       throw $this->createNotFoundException("La publication a été supprimée");
    }
  }

public function wallAction($page)
  {
    if ($page < 1) {
      throw new NotFoundHttpException('Page "'.$page.'" inexistante.');
    }

    $nbPerPage = 5;
    $em = $this->getDoctrine()->getManager();
    $user = $this->getUser();

    $listFriends1 = $user->getMyFriends()->toArray();
    $listFriends2 = $user->getFriendsWithMe()->toArray();
    $listFriends =  array_merge($listFriends1, $listFriends2);

    $listPublications = $em->getRepository('PlatformBundle:Publication')->getFriendsPubli($page, $nbPerPage ,$listFriends);
    $nbPages = ceil(count($listPublications)/$nbPerPage);
    
    return $this->render('PlatformBundle:Publication:wall.html.twig', array( 'listPublications' =>  $listPublications,
                                                                              'nbPages' => $nbPages,
                                                                              'page' => $page ) );
  }

  public function commentAction($id, Request $request)
  {
    if (!$request->isXmlHttpRequest()) {
        return new JsonResponse(array('message' => 'accessible uniquement avec Ajax!'), 400);
    }

    $em = $this->getDoctrine()->getManager();

    $publication = $em->getRepository('PlatformBundle:Publication')->find($id);

    if ($publication === null) {
    
      return new JsonResponse(array('message' => "La publication d'id ".$id." n'existe pas."), 400);
    }
    
    $comment = new UserComments();
    $form = $this->createCreateForm($comment,$id);

    if ($form->handleRequest($request)->isValid()) {

      $user = $this->getUser();
      $comment->setUser($user);
      $comment->setPublication($publication);
      $comment->setDate( new \DateTime() );
      
      $em->persist($comment);
      $em->flush();
      
      //return new JsonResponse(array('message' => 'Success' ), 200);
      
      return new JsonResponse(array('image'    => $user->getImage()->getUrl(),
                                    'firstname'=> $user->getFirstname(),    
                                    'lastname' => $user->getLastname(),
                                    'userlink' => $this->generateUrl('user_view', array('id' => $user->getId() )),
                                    'comment'  => $comment->getTextcomment(),
                                    'date'     => $comment->getdate()->format('d-m-Y H:i:s') ), 200);
    }

    $response = new JsonResponse(
                        array(
                              'message' => 'Error',
                              'form' => $this->renderView('PlatformBundle:Publication:comment.html.twig',
                                array(
                                      'entity' => $entity,
                                      'form' => $form->createView(),
                      ))), 400);
 
    return $response;

  }

    
  }

 ?>

src/OCPlatformBundle/Resources/views/Publication/add.html.twig
    {% extends "OCPlatformBundle::layout.html.twig" %}


    {% block title %} Ajout d'une annonce - {{ parent()  }}   {% endblock %}


    {% block ocplatform_body %}

        <h2>Ajouter une annonce</h2>
        {{ include( "OCPlatformBundle:Advert:form.html.twig") }}

        <p>
            Vous ajouter une nouvelle annonce merci de ne pas changer 
            l'esprit général des l'annonces publiées.
        </p>
        <p>
            
             <a href="{{ path('oc_platform_home') }}"  class="btn btn-default">
                <i class="glyphicon  glyphicon-chevron-left"></i>
                 Retour à la liste
            </a>
        </p>
       

    {% endblock  %}

src/OCPlatformBundle/Resources/views/Publication/comment.html.twig
<div class="well">
	<div class="form_error"></div>
	{{ form_start(form, {'attr': {'class': 'form-horizontal ajaxForm'}}) }}
	{{ form_errors(form) }}

	 <div class="form-group">
      {# {{ form_label(form.textcomment, "commentaire", {'label_attr': {'class': 'control-label col-sm-2'}}) }} #}
      {{ form_errors(form.textcomment) }}
      <div class="control-label col-sm-2" > <img class="img-thumbnail" src="{{ app.user.image.url }}"  alt="..."  style="max-height: 80px; max-width: 80px;"></div>
      <div class="col-sm-10">
        {{ form_widget(form.textcomment, {'attr': {'class': 'form-control', 'rows': 4 }}) }}
      </div>
    </div>

    <div class="form-group"> 
  		<div class="col-sm-offset-2 col-sm-10">
  			{{ form_widget(form.Ajouter, {'attr': {'class': 'btn btn-primary'}}) }}
  		</div>
	</div>

	{{ form_rest(form) }}

	{{ form_end(form) }}

</div>

src/OCPlatformBundle/Resources/views/Publication/delete.html.twig
    {% extends "OCPlatformBundle::layout.html.twig" %}


    {% block title %} Supprimer une annonce - {{ parent()  }}   {% endblock %}


    {% block ocplatform_body %}

        <h2>Supprimer une annonce</h2>
        

        <p>
            Êtes-vous certain de vouloir supprimez l'annonce "{{ advert.title }}" ? 
        </p>
        <form  action="{{ path('oc_platform_delete', {'id': advert.id}) }}" method="post" >
            
             <a href="{{ path('oc_platform_view', {'id': advert.id}) }}"  class="btn btn-default">
                <i class="glyphicon  glyphicon-chevron-left"></i>
                 Retour à l'annonce
            </a>

            <input type="submit" value="Supprimer" class="btn btn-danger" >

            {{ form_rest(form) }}

        </form>
       

    {% endblock  %}

src/OCPlatformBundle/Resources/views/Publication/edit.html.twig
    {% extends "OCPlatformBundle::layout.html.twig" %}


    {% block title %} Modifier d'une annonce - {{ parent()  }}   {% endblock %}


    {% block ocplatform_body %}

        <h2>Modifier une annonce</h2>
        {{ include( "OCPlatformBundle:Advert:form.html.twig") }}

        <p>
            Vous éditer une annonce déjà existante merci de ne pas changer 
            l'esprit général de l'annonce déjà publiée.
        </p>
        <p>
            
             <a href="{{ path('oc_platform_view' , {'id': advert.id }) }}"  class="btn btn-default">
                <i class="glyphicon  glyphicon-chevron-left"></i>
                Retour à la l'annonce
            </a>
        </p>
       

    {% endblock  %}

src/OCPlatformBundle/Resources/views/Publication/form.html.twig
<h3>Formulaire d'annonce</h3>
<div class="well" >
	{{ form_start(form, { 'attr' : { 'class' : 'form-horizontal' } } ) }}

		{{ form_errors(form) }}

		<div class="form-group" >
			{{ form_label(form.title, "Titre de l'annonce", { 'label_attr' : { 'class' : 'col-sm-3 control-label' } } ) }}

			{{ form_errors(form.title) }}			

			<div class="col-sm-4"> 
				{{ form_widget(form.title, { 'attr' : { 'class' : 'form-control' } } ) }}				
			</div>
		</div>


		<div class="form-group" >
			{{ form_label(form.content, "Contenu de l'annonce", { 'label_attr' : { 'class' : 'col-sm-3 control-label' } } ) }}

			{{ form_errors(form.content) }}			

			<div class="col-sm-4"> 
				{{ form_widget(form.content, { 'attr' : { 'class' : 'form-control' } } ) }}				
			</div>
		</div>

		{% if form.date is defined %}
		<div class="form-group" >
			{{ form_label(form.date, "Date", { 'label_attr' : { 'class' : 'col-sm-3 control-label' } } ) }}

			{{ form_errors(form.date) }}			

			<div class="col-sm-4" > 
				{{ form_widget(form.date, { 'attr' : { 'class' : 'form-control' } } ) }}				
			</div>
		</div>
		{% endif %}

		<div class="form-group" >
			{{ form_label(form.author, "Autheur", { 'label_attr' : { 'class' : 'col-sm-3 control-label' } } ) }}

			{{ form_errors(form.author) }}			

			<div class="col-sm-4"> 
				{{ form_widget(form.author, { 'attr' : { 'class' : 'form-control' } } ) }}				
			</div>
		</div>

		{% if form.date is defined %}
		<div class="form-group" >
			{{ form_label(form.published, "Publier", { 'label_attr' : { 'class' : 'col-sm-3 control-label' } } ) }}

			{{ form_errors(form.published) }}			

			<div class="col-sm-4"> 
				{{ form_widget(form.published, { 'attr' : { 'class' : 'form-control' } } ) }}				
			</div>
		</div>
		{% endif %}

		{{ form_row(form.image) }}

		{{ form_row(form.categories) }}

		{{ form_widget(form.save, { 'attr' : { 'class' : 'btn btn-primary' } } ) }}

		{{ form_rest(form) }}


	{{ form_end(form) }}

</div>

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" ></script>

<script type="text/javascript">
	$(document).ready( function(){

		var $container = $('div#ocplatformbundle_advert_categories');

		var $addLink = $('<a  href="#" id="add_category"  class="btn btn-default"  >Ajouter une catégorie</a>');

		$container.append($addLink);

		$addLink.click( function(e){

			addCategory($container); 
			e.preventDefault();
			return false;

		});

		var index = $container.find(':input').length;

		if (index==0) {
			addCategory($container);
		} else{
			$container.children('div').each( function(){
						addDeleteLink($(this));	 
			});
		}

		function addCategory($container) {
			
			$prototype = $($container.attr('data-prototype').replace( /__name__label__/g, 'Catégorie n°' + (index + 1 )  )
							.replace( /__name__/g, index )); 
			addDeleteLink($prototype);

			$container.append($prototype);

			index++;
		}

		function addDeleteLink($prototype) {
			

		$deleteLink = $('<a  href="#"  class="btn btn-danger"  >Supprimer</a>');

		$prototype.append($deleteLink);

		$deleteLink.click( function(e){

			$prototype.remove();
			e.preventDefault();
			return false;

		});

		}

		});
	
</script>

src/OCPlatformBundle/Resources/views/Publication/index.html.twig
    {% extends "OCPlatformBundle::layout.html.twig" %}


    {% block title %}  Acceuil - {{ parent()  }}   {% endblock %}


    {% block ocplatform_body %}
    
        <ul>
            {% for advert in listAdverts %}
                <li>
                    <a href="{{ path('oc_platform_view', {'id': advert.id })   }}">
                        {{ advert.title }}
                    </a>
                    par {{ advert.author }},
                    le {{ advert.date|date('d/m/Y')}}

                </li>
            {% else %}
                <li>Pas encore d'annonces </li>
            {% endfor  %}   
        </ul>       
        <ul class="pagination">
            {% for p in range(1,nbPages) %}
            <li {% if p == page  %} class="active" {% endif %} >
                <a href="{{ path('oc_platform_home', {'page': p }) }}"> {{p}} </a>
            </li>
            {% endfor  %}   
        </ul> 

    {% endblock  %}


    

src/OCPlatformBundle/Resources/views/Publication/menu.html.twig
<ul class="nav nav-pills nav-stacked">
  {% for advert in listAdverts %}
    <li>
      <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
        {{ advert.title }}
      </a>
    </li>
  {% endfor %}
</ul>

src/OCPlatformBundle/Resources/views/Publication/view.html.twig
    {% extends "OCPlatformBundle::layout.html.twig" %}


    {% block title %}  Lecture d'une annonce - {{ parent()  }}   {% endblock %}


    {% block ocplatform_body %}
   
    {% if advert.image is not null %}
        <img src="{{ asset(advert.image.webPath) }}" alt="{{advert.image.alt}}" >
    {% endif %}

        <h2>{{ advert.title }}</h2>

        <i> Par {{advert.author}}, le {{ advert.date|date('d/m/Y') }} </i>

        <div class="well">
            {{ advert.content }}
        </div>
    
        <p>
            
            <a href="{{ path('oc_platform_home') }}"  class="btn btn-default">
                <i class="glyphicon  glyphicon-chevron-left"></i>
                 Retour à la liste
            </a>
             <a href="{{ path('oc_platform_edit', {'id': advert.id }) }}"  class="btn btn-default">
                <i class="glyphicon glyphicon-edit"></i>
                 Modifier l'annonce
            </a>
             <a href="{{ path('oc_platform_delete', {'id': advert.id })   }}"  class="btn btn-danger"> 
                <i class="glyphicon glyphicon-trash"></i>
                 Supprimer l'annonce
            </a>
        </p>

        {% if  not advert.categories.empty %}
        <p>
            Cette annonce est parue dans les catégories suivantes :
            {% for category in advert.categories %}
                {{category.name}}{% if not loop.last %}, {% endif %}
            {% endfor %}
        </p>
        {% endif %}

        {% if listAdvertSkills|length > 0 %}
        <div>
            Cette annonce requiert les compétences suivantes :
            <ul>
                {% for advertSkill in listAdvertSkills %}
                <li>{{ advertSkill.skill.name }}: niveau {{advertSkill.level}}</li>
                {% endfor %}    
            </ul>
        </div>
        {% endif %}

        <ul class="list-unstyled">
                {% for application in listApplications %}
                    <li> <i> Par {{ application.author }}, le {{ application.date|date('d/m/Y') }}   </i>  
                        <div class="well"> {{application.content}}  </div>
                     </li>
                {% else %}
                    <li>Pas de candidatures.</li>
                {% endfor %}
            </ul>

    {% endblock  %}

src/OCPlatformBundle/Resources/views/Publication/wall.html.twig
{% extends "PlatformBundle::layout.html.twig" %}

{% block title %}
  Journal - {{ parent() }}
{% endblock %}

{% block platform_body %}

 <h2>Votre Journal</h2>

 {% for publication in listPublications %}

 		 	<ul class="list-group" >
		<li class="list-group-item">
    		<div class="row">
       			 <div class="col-sm-12 col-md-6 col-lg-4">
           			 <img  class="img-thumbnail"  src="{{ publication.image.url }}" alt="..."/>  <!-- http://placehold.it/242x200 -->
        		</div>

        		<div class="col-sm-12 col-md-6 col-lg-8">
            		<div class="caption">
            			<div class="row">
            				<div class="col-sm-12 col-md-6 col-lg-2" >
            					<img class="img-thumbnail" src="{{ publication.author.image.url }}"  alt="..."  style="max-height: 80px; max-width: 80px;">
            				</div>
            				<div class="col-sm-12 col-md-6 col-lg-10"  >  
            					<p>
            					 <a href="{{ path('user_view', {'id': publication.author.id }) }}">
            					          {{publication.author.firstname}} {{publication.author.lastname}} 
            					  </a>
            					</p>
            					<p><small><i>Publié le {{ publication.date|date('d/m/Y H:i:s') }}</i></small></p>

            				  </div>
            			</div>
             			 <h3><a href="{{ path('publication_view', {'id': publication.id})  }}"> 
          				{{ publication.title }}
        				</a></h3>
                  {% if publication.origin %}
                  <p>
                    <a href="{{ path('publication_view', {'id': publication.origin.id}) }}"> {{ publication.origin.title }}
                    </a>
                  </p>
                  {% endif %}
            			 <p>{{publication.content}}
        				</p>
                  <p>
                    <a href="#" class="btn btn-primary" role="button">Commenter</a> 
                    <a href="{{ path( 'publication_share', {'id' : publication.id } ) }}" class="btn btn-default" role="button">Partager</a>
                    <a href="{{ path('user_like', {'id': publication.id}) }}" class="btn btn-default" title="J'aime" id="like" >
                    <i class="glyphicon glyphicon-thumbs-up"></i> 
                    <span id="likes" class="badge">{{publication.likes}}</span></button> </a>  
                    
                  </p>

           			</div>
    			</div>

			</div>
		</li>
	 </ul>


 {% else %}
     <p>Pas (encore !) de publication</p>
 {% endfor %}

  <ul class="pagination">
            {% for p in range(1,nbPages) %}
              <li {% if p == page  %} class="active" {% endif %} >
                <a href="{{ path('platform_wall', {'page': p }) }}"> {{p}} </a> 
              </li>
            {% endfor  %}   
  	</ul> 


{% endblock %}